' Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml DetailsKunde

'top to bottom direction

rectangle DetailsKunde
rectangle Waiting
rectangle DetailsBreadcrumbs
rectangle DetailsStammdaten
rectangle DetailsAdresse
rectangle DetailsBearbeiten

DetailsKunde --> Waiting
DetailsKunde --> DetailsBreadcrumbs
DetailsKunde --> DetailsStammdaten
DetailsKunde --> DetailsAdresse
DetailsKunde --> DetailsBearbeiten

rectangle DetailsKategorie
rectangle DetailsNachname
rectangle DetailsEmail
rectangle DetailsHomepage
rectangle DetailsFamilienstand
rectangle DetailsGeburtsdatum
rectangle DetailsHasNewsletter
rectangle DetailsInteressen

DetailsStammdaten --> DetailsKategorie
DetailsStammdaten --> DetailsNachname
DetailsStammdaten --> DetailsEmail
DetailsStammdaten --> DetailsHomepage
DetailsStammdaten --> DetailsFamilienstand
DetailsStammdaten --> DetailsGeburtsdatum
DetailsStammdaten --> DetailsHasNewsletter
DetailsStammdaten --> DetailsInteressen

rectangle DetailsOrt
rectangle DetailsPlz

DetailsAdresse --> DetailsOrt
DetailsAdresse --> DetailsPlz

@enduml
